language: node_js
node_js:
  - "node"
  - "4"
  - "6"
  - "8"
sudo: false
before_script:
  - psql -c 'create database test;' -U postgres
before_install:

after_success:
  npm test
env:
  global:
    - DATABASE_URL=postgres://postgres:@localhost/test
addons:
  postgresql: "9.6"
