language:
  node_js
node_js:
  - "node"
  - "4"
  - "6"
  - "8"
sudo: false
install:
script:
  - npm test
before_script:
  - psql -c 'create database test;' -U postgres
env:
  global:
    - DATABASE_URL=postgres://postgres:@localhost/test
    - PGHOST=localhost
    - PGPORT=5432
    - PGDATABASE=postgres
    - PGUSER=postgres
addons:
  postgresql: "9.6"
