language:
  node_js
node_js:
  - "node"
  - "4"
  - "6"
  - "8"
sudo: false
install:
  - npm install -g codecov
script:
  - npm test
  - codecov
before_script:
  - psql -c 'create database test;' -U postgres
env:
  global:
    - DATABASE_URL=postgres://postgres:@localhost/test
addons:
  postgresql: "9.6"
